# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/Ejercicio_17/Ejercicio_17.srcs/sources_1/ip/pcMem/pcMem.xci
# IP: The module: 'pcMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/Ejercicio_17/Ejercicio_17.gen/sources_1/ip/pcMem/pcMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcMem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/Ejercicio_17/Ejercicio_17.srcs/sources_1/ip/pcMem/pcMem.xci
# IP: The module: 'pcMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/Ejercicio_17/Ejercicio_17.gen/sources_1/ip/pcMem/pcMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
